-- 코드를 입력하세요
SELECT  CATEGORY as CATEGORY , sum(SALES) as TOTAL_SALES
FROM BOOK as A
INNER JOIN BOOK_SALES as B
    ON A.BOOK_ID = B.BOOK_ID
WHERE B.SALES_DATE BETWEEN '2022-01-01' AND'2022-01-31'
GROUP BY A.CATEGORY
ORDER BY CATEGORY asc