-- 코드를 입력하세요
SELECT PRODUCT_CODE,SUM(B.SALES_AMOUNT * A.PRICE)
FROM PRODUCT A
INNER JOIN OFFLINE_SALE B
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE
ORDER BY SUM(B.SALES_AMOUNT * A.PRICE) DESC, PRODUCT_CODE ASC;