-- 코드를 입력하세요
SELECT TO_CHAR(DATETIME,'HH24') , COUNT(TO_CHAR(DATETIME,'HH24'))
FROM ANIMAL_OUTS 
GROUP BY TO_CHAR(DATETIME,'HH24') 
HAVING TO_CHAR(DATETIME,'HH24')<20 AND TO_CHAR(DATETIME,'HH24') >8
ORDER BY TO_CHAR(DATETIME,'HH24') ASC;